/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Incio;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebas
 */
public class Matematica extends javax.swing.JFrame {

    ArrayList<String> preguntas = new ArrayList<>();
    ArrayList<String> opciones = new ArrayList<>();
    ArrayList<Integer> valopciones = new ArrayList<>();
    int n = 0, con = 0;

    /**
     * Creates new form Matematica
     */
    public Matematica() {
        initComponents(); cargarListas();
        Fin.setVisible(false);
        //jButton1.setVisible(false);
        txtContador.setText(String.valueOf(con));
    }

    public void cargarListas() {
        try {
            conexion cn = new conexion();
            Connection cc = cn.conectar();
            String sql = "select * from preguntas where id_materia_pregunta = 2";
            java.sql.Statement psd = cc.createStatement();
            ResultSet rs = psd.executeQuery(sql);
            while (rs.next()) {
                preguntas.add(rs.getString("descripcion_pregunta"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Lenguaje.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void limpiar() {
        opciones.clear();
        valopciones.clear();
    }

    public void preguntar(int posicion) {
        jlbNpregunt.setText("Pregunta # " + String.valueOf(posicion + 1));
        txtPregunta.setText(preguntas.get(posicion));
        int lp = posicion + 1;
        try {
            conexion cn = new conexion();
            Connection cc = cn.conectar();
            String sql = "select * from opciones where id_pregunta=" + lp;
            java.sql.Statement psd = cc.createStatement();
            ResultSet rs = psd.executeQuery(sql);
            while (rs.next()) {
                valopciones.add(rs.getInt("validacion_opcion"));
                opciones.add(rs.getString("descripcion_opcion"));
            }
            jrbResp1.setText(opciones.get(0));
            jrbResp2.setText(opciones.get(1));
            jrbResp3.setText(opciones.get(2));
        } catch (SQLException ex) {
            Logger.getLogger(Lenguaje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPregunta = new javax.swing.JLabel();
        jbtnMenuPrinci = new javax.swing.JButton();
        jbtnContinuar = new javax.swing.JButton();
        jbtnAtras = new javax.swing.JButton();
        jbtnCerSes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jrbResp1 = new javax.swing.JCheckBox();
        jrbResp2 = new javax.swing.JCheckBox();
        jrbResp3 = new javax.swing.JCheckBox();
        txtContador = new javax.swing.JLabel();
        jlbNpregunt = new javax.swing.JLabel();
        Fin = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnMenuPrinci.setText("Menu Principal");

        jbtnContinuar.setText("Continuar");
        jbtnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnContinuarActionPerformed(evt);
            }
        });

        jbtnAtras.setText("Atras");

        jbtnCerSes.setText("Cerrar Sesión");
        jbtnCerSes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerSesActionPerformed(evt);
            }
        });

        jrbResp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbResp1MouseClicked(evt);
            }
        });
        jrbResp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbResp1ActionPerformed(evt);
            }
        });

        jrbResp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbResp2MouseClicked(evt);
            }
        });

        jrbResp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbResp3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbResp3, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbResp2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbResp1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jrbResp1)
                .addGap(18, 18, 18)
                .addComponent(jrbResp2)
                .addGap(18, 18, 18)
                .addComponent(jrbResp3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Fin.setText("Fin del juego");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnCerSes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbNpregunt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jbtnAtras)
                        .addGap(63, 63, 63)
                        .addComponent(jbtnContinuar)
                        .addGap(59, 59, 59)
                        .addComponent(jbtnMenuPrinci))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(Fin, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtnCerSes)
                                .addGap(5, 5, 5))
                            .addComponent(jlbNpregunt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(txtPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnContinuar)
                    .addComponent(jbtnAtras)
                    .addComponent(jbtnMenuPrinci))
                .addGap(18, 18, 18)
                .addComponent(Fin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbResp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbResp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbResp1ActionPerformed

    private void jbtnCerSesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerSesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCerSesActionPerformed

    private void jbtnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnContinuarActionPerformed
        // TODO add your handling code here:
        jrbResp1.setEnabled(true);
        jrbResp2.setEnabled(true);
        jrbResp3.setEnabled(true);
        jrbResp1.setSelected(false);
        jrbResp2.setSelected(false);
        jrbResp3.setSelected(false);

        limpiar();
        n += 1;
        if (n < preguntas.size()) {
            preguntar(n);
        } else {
            jrbResp1.setEnabled(false);
            jrbResp2.setEnabled(false);
            jrbResp3.setEnabled(false);
            Fin.setText("Fin del juego");
            Fin.setVisible(true);
            jbtnContinuar.setVisible(false);
        }
    }//GEN-LAST:event_jbtnContinuarActionPerformed

    private void jrbResp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbResp1MouseClicked
        // TODO add your handling code here:
        if (valopciones.get(0) == 1) {
            txtContador.setText(String.valueOf(con += 20));
            jrbResp2.setEnabled(false);
            jrbResp3.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(this, "Respuesta incorrecta, intente de nuevo");
            jrbResp1.setEnabled(false);
            jrbResp1.setSelected(false);
        }
    }//GEN-LAST:event_jrbResp1MouseClicked

    private void jrbResp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbResp2MouseClicked
        // TODO add your handling code here:
        if (valopciones.get(1) == 1) {
            txtContador.setText(String.valueOf(con += 20));
            jrbResp1.setEnabled(false);
            jrbResp3.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(this, "Respuesta incorrecta, intente de nuevo");
            jrbResp2.setEnabled(false);
            jrbResp2.setSelected(false);
        }
    }//GEN-LAST:event_jrbResp2MouseClicked

    private void jrbResp3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbResp3MouseClicked
        // TODO add your handling code here:
        if (valopciones.get(2) == 1) {
            txtContador.setText(String.valueOf(con += 20));
            jrbResp1.setEnabled(false);
            jrbResp2.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(this, "Respuesta incorrecta, intente de nuevo");
            jrbResp3.setEnabled(false);
            jrbResp3.setSelected(false);
        }
    }//GEN-LAST:event_jrbResp3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matematica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAtras;
    private javax.swing.JButton jbtnCerSes;
    private javax.swing.JButton jbtnContinuar;
    private javax.swing.JButton jbtnMenuPrinci;
    private javax.swing.JLabel jlbNpregunt;
    private javax.swing.JCheckBox jrbResp1;
    private javax.swing.JCheckBox jrbResp2;
    private javax.swing.JCheckBox jrbResp3;
    private javax.swing.JLabel txtContador;
    private javax.swing.JLabel txtPregunta;
    // End of variables declaration//GEN-END:variables
}
