/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Incio;

import javax.swing.JOptionPane;

/**
 *
 * @author Sebas
 */
public class Pregunta2Matematica extends javax.swing.JFrame {

    /**
     * Creates new form Pregunta2Matematica
     */
    public Pregunta2Matematica() {
        initComponents();
        jlbPuntaje1.setText("0001");
        jbtnContinuar1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jbtnContinuar = new javax.swing.JButton();
        btnRes1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRes3 = new javax.swing.JButton();
        btnRes2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jlbPuntaje = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jbtnContinuar1 = new javax.swing.JButton();
        btnRes4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnRes5 = new javax.swing.JButton();
        btnRes6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jlbPuntaje1 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Cuanto es 2+2?");

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton4.setText("Salir");

        jbtnContinuar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtnContinuar.setText("Continuar");

        btnRes1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnRes1.setText("a) 1");
        btnRes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRes1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setText("Puntaje:");

        btnRes3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnRes3.setText("c) 4");
        btnRes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRes3ActionPerformed(evt);
            }
        });

        btnRes2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnRes2.setText("b) 6");
        btnRes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRes2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("Volver");

        jlbPuntaje.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlbPuntaje.setText("0000");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Cuanto es 4/2?");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jbtnContinuar1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbtnContinuar1.setText("Continuar");

        btnRes4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnRes4.setText("a) 2");
        btnRes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRes4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setText("Puntaje:");

        btnRes5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnRes5.setText("c) 1");
        btnRes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRes5ActionPerformed(evt);
            }
        });

        btnRes6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnRes6.setText("b) 5");
        btnRes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRes6ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jlbPuntaje1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlbPuntaje1.setText("0000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jlbPuntaje1)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRes6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRes4)
                            .addComponent(btnRes5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(61, 61, 61)
                                .addComponent(jbtnContinuar1)))
                        .addGap(57, 57, 57)
                        .addComponent(jButton5)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPuntaje1)
                    .addComponent(jLabel7))
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addComponent(btnRes4)
                .addGap(18, 18, 18)
                .addComponent(btnRes6)
                .addGap(26, 26, 26)
                .addComponent(btnRes5)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jbtnContinuar1)
                    .addComponent(jButton5))
                .addGap(0, 90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRes1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Respuesta incorrecta");
        btnRes1.setEnabled(false);
        jbtnContinuar1.setEnabled(false);
    }//GEN-LAST:event_btnRes1ActionPerformed

    private void btnRes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRes3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Respuesta correcta, felicidades");
        jlbPuntaje1.setText("0002");
        btnRes3.setEnabled(false);
        jbtnContinuar1.setEnabled(true);
    }//GEN-LAST:event_btnRes3ActionPerformed

    private void btnRes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRes2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Respuesta incorrecta");
        btnRes2.setEnabled(false);
    }//GEN-LAST:event_btnRes2ActionPerformed

    private void btnRes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRes4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Respuesta correcta, felicidades");
        jlbPuntaje1.setText("0002");
        btnRes1.setEnabled(false);
        jbtnContinuar1.setEnabled(true);
        btnRes1.setEnabled(false);
        btnRes5.setEnabled(false);
        btnRes6.setEnabled(false);
    }//GEN-LAST:event_btnRes4ActionPerformed

    private void btnRes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRes5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Respuesta incorrecta");
        btnRes5.setEnabled(false);
    }//GEN-LAST:event_btnRes5ActionPerformed

    private void btnRes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRes6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Respuesta incorrecta");
        btnRes6.setEnabled(false);
    }//GEN-LAST:event_btnRes6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JuegoMenu j = new JuegoMenu();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pregunta2Matematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pregunta2Matematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pregunta2Matematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pregunta2Matematica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pregunta2Matematica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRes1;
    private javax.swing.JButton btnRes2;
    private javax.swing.JButton btnRes3;
    private javax.swing.JButton btnRes4;
    private javax.swing.JButton btnRes5;
    private javax.swing.JButton btnRes6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtnContinuar;
    private javax.swing.JButton jbtnContinuar1;
    private javax.swing.JLabel jlbPuntaje;
    private javax.swing.JLabel jlbPuntaje1;
    // End of variables declaration//GEN-END:variables
}
